var gnss = {
"type": "FeatureCollection",
"name": "gnss",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "fid": 147, "Name": "1", "Code": "GPS031", "Control code": null, "Easting": 803622.449, "Northing": 8528844.263, "Elevation": 2901.265, "Description": null, "Longitude": -72.19781394, "Latitude": -13.29218454, "Ellipsoidal height": 2946.977, "Origin": "Local", "Tilt angle": null, "Easting RMS": null, "Northing RMS": null, "Elevation RMS": null, "Lateral RMS": null, "Antenna height": null, "Antenna height units": "m", "Solution status": null, "Correction type": null, "Averaging start": null, "Averaging end": null, "Samples": null, "PDOP": null, "GDOP": null, "Base easting": null, "Base northing": null, "Base elevation": null, "Base longitude": null, "Base latitude": null, "Base ellipsoidal height": null, "Baseline": null, "Mount point": null, "CS name": "WGS 84 / UTM zone 18S + EGM2008 height", "GPS Satellites": null, "GLONASS Satellites": null, "Galileo Satellites": null, "BeiDou Satellites": null, "QZSS Satellites": null }, "geometry": { "type": "Point", "coordinates": [ -72.197813941388702, -13.292184536567238 ] } },
{ "type": "Feature", "properties": { "fid": 148, "Name": "2", "Code": "GPS032", "Control code": null, "Easting": 803518.641, "Northing": 8528782.323000001, "Elevation": 2921.23, "Description": null, "Longitude": -72.19876477, "Latitude": -13.29275451, "Ellipsoidal height": 2966.938, "Origin": "Local", "Tilt angle": null, "Easting RMS": null, "Northing RMS": null, "Elevation RMS": null, "Lateral RMS": null, "Antenna height": null, "Antenna height units": "m", "Solution status": null, "Correction type": null, "Averaging start": null, "Averaging end": null, "Samples": null, "PDOP": null, "GDOP": null, "Base easting": null, "Base northing": null, "Base elevation": null, "Base longitude": null, "Base latitude": null, "Base ellipsoidal height": null, "Baseline": null, "Mount point": null, "CS name": "WGS 84 / UTM zone 18S + EGM2008 height", "GPS Satellites": null, "GLONASS Satellites": null, "Galileo Satellites": null, "BeiDou Satellites": null, "QZSS Satellites": null }, "geometry": { "type": "Point", "coordinates": [ -72.198764769761468, -13.292754505660735 ] } }
]
}
